apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: default
  labels:
    app: nodejs-app
spec:
  type: LoadBalancer        # AWS automatically creates an ELB
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80              # External port (browser access)
      targetPort: 3000      # Node.js app port inside container
